// Quota service — tracks AI message usage per shop per month and enforces
// the cahier des charges quota rules (ch. 7.2 — Quotas et dépassements).
//
// Lifecycle of a quota check:
//  1. The AI engine calls IsInDegradedMode(shopID) BEFORE calling the LLM.
//     If the shop has used ≥ 100% of its monthly message quota, the engine
//     returns the degraded-mode response (NOVA stops non-essential
//     auto-responses) and escalates to the merchant.
//  2. After each successful AI call, the engine calls IncrementUsage(...).
//     This inserts a row in ai_usage AND re-evaluates the thresholds. When
//     the 80% or 100% boundary is crossed, a notification is created for
//     the shop owner (ch. 7.2 — alerts at 80% and 100%).
//  3. The ResetMonthlyQuotas cron runs on the 1st of each month. Because
//     ai_usage is append-only and scoped by date_trunc('month', created_at),
//     "resetting" means simply that the monthly count naturally starts from
//     0 for the new month — we don't need to truncate the table.
//
// The "messages" counted by this service are ai_usage rows (one per LLM call)
// — NOT conversations.messages rows. A conversation with 5 customer messages
// + 5 AI replies produces 5 ai_usage rows = 5 quota units. This matches the
// cahier des charges (ch. 7.2 — "messages IA").
package services

import (
        "context"
        "encoding/json"
        "errors"
        "fmt"
        "time"

        "github.com/google/uuid"
        "github.com/jackc/pgx/v5/pgxpool"
        "log/slog"

        "nova-api/internal/models"
        "nova-api/internal/repository"
)

// Quota service sentinel errors.
var (
        ErrQuotaServiceNotInitialized = errors.New("quota service not initialized")
        ErrPlanNotFoundForQuota       = errors.New("plan not found for quota check")
)

// QuotaConfig holds the runtime knobs for the quota service.
type QuotaConfig struct {
        Threshold80  int // percent of the monthly quota that triggers the first alert (default 80)
        Threshold100 int // percent that triggers degraded mode (default 100)
}

// DefaultQuotaConfig returns the standard thresholds.
func DefaultQuotaConfig() QuotaConfig {
        return QuotaConfig{Threshold80: 80, Threshold100: 100}
}

// QuotaService is the quota tracking + enforcement layer.
type QuotaService struct {
        planRepo  *repository.PlanRepository
        subRepo   *repository.SubscriptionRepository
        usageRepo *repository.AIUsageRepository
        notifRepo *repository.NotificationsRepository
        auditRepo *repository.AuditRepository
        pool      *pgxpool.Pool
        cfg       QuotaConfig
        log       *slog.Logger
}

// NewQuotaService constructs a QuotaService. cfg may be zero — defaults are
// applied. log may be nil — slog.Default() is used.
func NewQuotaService(
        planRepo *repository.PlanRepository,
        subRepo *repository.SubscriptionRepository,
        usageRepo *repository.AIUsageRepository,
        notifRepo *repository.NotificationsRepository,
        auditRepo *repository.AuditRepository,
        pool *pgxpool.Pool,
        cfg QuotaConfig,
        log *slog.Logger,
) *QuotaService {
        if cfg.Threshold80 <= 0 {
                cfg.Threshold80 = 80
        }
        if cfg.Threshold100 <= 0 {
                cfg.Threshold100 = 100
        }
        if log == nil {
                log = slog.Default()
        }
        return &QuotaService{
                planRepo:  planRepo,
                subRepo:   subRepo,
                usageRepo: usageRepo,
                notifRepo: notifRepo,
                auditRepo: auditRepo,
                pool:      pool,
                cfg:       cfg,
                log:       log,
        }
}

// QuotaAlert is one alert generated by CheckQuota (e.g. "80% of quota
// reached", "100% — degraded mode"). The dashboard surfaces these in the
// banner.
type QuotaAlert struct {
        Level   string `json:"level"` // "info" | "warning" | "critical"
        Code    string `json:"code"`  // "quota_80" | "quota_100" | "quota_exceeded"
        Message string `json:"message"`
}

// QuotaStatus is the result of CheckQuota — the dashboard uses it to render
// the quota widget and the degraded-mode banner.
type QuotaStatus struct {
        PlanName          string       `json:"plan_name"`
        MessageQuota      int          `json:"message_quota"`
        MessagesUsed      int          `json:"messages_used"`
        MessagesRemaining int          `json:"messages_remaining"`
        UsagePercent      float64      `json:"usage_percent"`
        IsAt80Percent     bool         `json:"is_at_80_percent"`
        IsAt100Percent    bool         `json:"is_at_100_percent"`
        IsInDegradedMode  bool         `json:"is_in_degraded_mode"`
        Alerts            []QuotaAlert `json:"alerts"`
}

// CheckQuota returns the current quota status for the shop. It does NOT
// mutate state — alerts are generated here purely for the dashboard's
// convenience. The actual notification creation happens in IncrementUsage
// when a threshold is crossed.
func (s *QuotaService) CheckQuota(ctx context.Context, shopID uuid.UUID) (*QuotaStatus, error) {
        if s == nil || s.usageRepo == nil {
                return nil, ErrQuotaServiceNotInitialized
        }
        // Fetch the subscription to get the plan_id.
        sub, err := s.subRepo.GetByShopID(ctx, uuid.Nil, string(models.RoleSuperAdmin), shopID)
        if err != nil {
                if errors.Is(err, repository.ErrNotFound) {
                        return nil, ErrSubscriptionNotFound
                }
                return nil, fmt.Errorf("quota: get subscription: %w", err)
        }
        plan, err := s.planRepo.GetByID(ctx, sub.PlanID)
        if err != nil {
                return nil, ErrPlanNotFoundForQuota
        }
        used, err := s.usageRepo.CountMessagesThisMonth(ctx, shopID)
        if err != nil {
                return nil, fmt.Errorf("quota: count messages: %w", err)
        }
        usedInt := int(used)
        quota := plan.MessageQuota
        status := &QuotaStatus{
                PlanName:          plan.Name,
                MessageQuota:      quota,
                MessagesUsed:      usedInt,
                MessagesRemaining: quota - usedInt,
                Alerts:            []QuotaAlert{},
        }
        if quota > 0 {
                status.UsagePercent = float64(usedInt) / float64(quota) * 100.0
        }
        if status.MessagesRemaining < 0 {
                status.MessagesRemaining = 0
        }
        if status.UsagePercent >= float64(s.cfg.Threshold80) {
                status.IsAt80Percent = true
                status.Alerts = append(status.Alerts, QuotaAlert{
                        Level:   "warning",
                        Code:    "quota_80",
                        Message: fmt.Sprintf("Vous avez utilisé %d%% de votre quota mensuel (%d / %d messages).", int(status.UsagePercent), usedInt, quota),
                })
        }
        if status.UsagePercent >= float64(s.cfg.Threshold100) {
                status.IsAt100Percent = true
                status.IsInDegradedMode = true
                status.Alerts = append(status.Alerts, QuotaAlert{
                        Level:   "critical",
                        Code:    "quota_100",
                        Message: "Quota mensuel atteint — NOVA fonctionne en mode dégradé. Les messages sont transférés au commerçant.",
                })
        }
        return status, nil
}

// IsInDegradedMode returns true iff the shop has used ≥ 100% of its monthly
// message quota. The AI engine calls this BEFORE invoking the LLM (ch. 7.2 —
// at 100% NOVA stops non-essential auto-responses). When this returns true,
// the engine skips the LLM call entirely (cost saving) and returns the
// degraded-mode response via GetDegradedModeResponse().
func (s *QuotaService) IsInDegradedMode(ctx context.Context, shopID uuid.UUID) (bool, error) {
        if s == nil || s.usageRepo == nil {
                return false, ErrQuotaServiceNotInitialized
        }
        sub, err := s.subRepo.GetByShopID(ctx, uuid.Nil, string(models.RoleSuperAdmin), shopID)
        if err != nil {
                // If no subscription: not in degraded mode (the AI flow will fail later).
                if errors.Is(err, repository.ErrNotFound) {
                        return false, nil
                }
                return false, fmt.Errorf("quota: get subscription: %w", err)
        }
        plan, err := s.planRepo.GetByID(ctx, sub.PlanID)
        if err != nil {
                return false, nil // best-effort — don't block the AI on a missing plan
        }
        if plan.MessageQuota <= 0 {
                return false, nil // unlimited quota
        }
        used, err := s.usageRepo.CountMessagesThisMonth(ctx, shopID)
        if err != nil {
                return false, fmt.Errorf("quota: count messages: %w", err)
        }
        return int(used) >= plan.MessageQuota, nil
}

// GetDegradedModeResponse returns the message NOVA sends to the customer
// when the shop is in degraded mode (ch. 7.2 — at 100% the customer message
// is forwarded to the merchant, NOVA replies with a neutral auto-reply and
// a pack proposal is sent to the merchant out-of-band).
//
// The merchant is notified separately via IncrementUsage → notification.
func GetDegradedModeResponse() string {
        return "Notre service a atteint sa capacité mensuelle. Un commerçant va vous répondre."
}

// IncrementUsage records one AI call (tokens, latency, cost) and re-evaluates
// the 80% / 100% thresholds. When a threshold is crossed for the first time
// in the current month, a notification is created for the shop owner.
//
// This method is called by the AI engine after every successful LLM call.
// It must be fast (one INSERT + one COUNT) and best-effort (a logging failure
// must NOT block the AI flow).
func (s *QuotaService) IncrementUsage(
        ctx context.Context,
        shopID, conversationID uuid.UUID,
        model string,
        tokensIn, tokensOut, latencyMs int,
        cost float64,
) error {
        if s == nil || s.usageRepo == nil {
                return ErrQuotaServiceNotInitialized
        }
        // 1. Insert the ai_usage row.
        if err := s.usageRepo.Record(ctx, shopID, conversationID, model, tokensIn, tokensOut, latencyMs, cost); err != nil {
                return fmt.Errorf("quota: record usage: %w", err)
        }
        // 2. Re-evaluate thresholds (best-effort — log on error, don't fail the AI call).
        s.maybeAlertThresholds(ctx, shopID)
        return nil
}

// maybeAlertThresholds checks the current usage against the plan quota and
// creates a notification if the 80% or 100% threshold was just crossed. The
// dedup is done by checking whether a notification of the same type already
// exists for this shop in the current month (via NotificationsRepository.
// ExistsThisMonth). Without this dedup, every IncrementUsage call after the
// threshold is crossed would create a new notification (potentially hundreds
// per day, one per AI call).
//
// All errors are logged and swallowed — this method is best-effort.
func (s *QuotaService) maybeAlertThresholds(ctx context.Context, shopID uuid.UUID) {
        if s.notifRepo == nil {
                return
        }
        status, err := s.CheckQuota(ctx, shopID)
        if err != nil {
                s.log.Warn("quota: check for alerts failed", "error", err, "shop_id", shopID)
                return
        }
        // Build the alert payload.
        if status.IsAt100Percent {
                // Dedup — only create the 100% alert once per shop per month.
                already, err := s.notifRepo.ExistsThisMonth(ctx, &shopID, "quota_100_reached")
                if err != nil {
                        s.log.Warn("quota: dedup check (100%) failed", "error", err, "shop_id", shopID)
                } else if already {
                        // Already alerted this month — don't spam.
                        return
                }
                payload, _ := json.Marshal(map[string]any{
                        "shop_id":       shopID.String(),
                        "used":          status.MessagesUsed,
                        "quota":         status.MessageQuota,
                        "percent":       int(status.UsagePercent),
                        "degraded_mode": true,
                        "plan_name":     status.PlanName,
                        "suggestion":    "Proposer un pack supplémentaire au commerçant.",
                })
                if _, err := s.notifRepo.Create(ctx, &shopID, nil, "quota_100_reached", payload); err != nil {
                        s.log.Warn("quota: create 100% notification failed", "error", err, "shop_id", shopID)
                }
                // Audit log.
                s.auditQuotaEvent(ctx, shopID, "quota.100_reached", status)
                return
        }
        if status.IsAt80Percent {
                // Dedup — only create the 80% alert once per shop per month.
                already, err := s.notifRepo.ExistsThisMonth(ctx, &shopID, "quota_80_reached")
                if err != nil {
                        s.log.Warn("quota: dedup check (80%) failed", "error", err, "shop_id", shopID)
                } else if already {
                        return
                }
                payload, _ := json.Marshal(map[string]any{
                        "shop_id":    shopID.String(),
                        "used":       status.MessagesUsed,
                        "quota":      status.MessageQuota,
                        "percent":    int(status.UsagePercent),
                        "plan_name":  status.PlanName,
                        "suggestion": "Vous approchez de votre quota mensuel. Pensez à souscrire un pack supplémentaire.",
                })
                if _, err := s.notifRepo.Create(ctx, &shopID, nil, "quota_80_reached", payload); err != nil {
                        s.log.Warn("quota: create 80% notification failed", "error", err, "shop_id", shopID)
                }
                s.auditQuotaEvent(ctx, shopID, "quota.80_reached", status)
        }
}

// auditQuotaEvent writes a quota threshold event to audit_logs (best-effort).
func (s *QuotaService) auditQuotaEvent(ctx context.Context, shopID uuid.UUID, action string, status *QuotaStatus) {
        if s.auditRepo == nil {
                return
        }
        after, _ := json.Marshal(map[string]any{
                "shop_id":       shopID.String(),
                "plan_name":     status.PlanName,
                "used":          status.MessagesUsed,
                "quota":         status.MessageQuota,
                "percent":       int(status.UsagePercent),
                "degraded_mode": status.IsInDegradedMode,
        })
        _ = s.auditRepo.Log(ctx, repository.AuditEntry{
                ShopID:     &shopID,
                ActorID:    nil,
                ActorRole:  "system",
                Action:     action,
                ObjectType: "subscription",
                After:      rawJSON{after},
        })
}

// ResetMonthlyQuotas is the cron-job entry point for the 1st-of-month quota
// reset. Because ai_usage is append-only and the monthly count is scoped by
// date_trunc('month', created_at), the new month naturally starts from 0
// without any truncation. This method is therefore a no-op kept for naming
// parity with the spec; we log a debug entry so operators can verify the cron
// is firing.
//
// In a future iteration we could trim very old ai_usage rows (> 12 months)
// here to keep the table small. We don't do it yet because the table is small
// and the historical data is useful for cost-rebalancing analyses (ch. 7.2).
func (s *QuotaService) ResetMonthlyQuotas(ctx context.Context) error {
        if s == nil {
                return ErrQuotaServiceNotInitialized
        }
        s.log.Info("quota: monthly reset (no-op — ai_usage is append-only, monthly count naturally resets at month boundary)",
                "now", time.Now().UTC().Format(time.RFC3339))
        return nil
}

// QuotaServiceIface is the narrow interface the AI engine uses to check the
// degraded-mode flag + record usage. Defined here so the engine can depend
// on the interface (not the concrete *QuotaService) — useful for testing.
type QuotaServiceIface interface {
        IsInDegradedMode(ctx context.Context, shopID uuid.UUID) (bool, error)
        IncrementUsage(ctx context.Context, shopID, conversationID uuid.UUID, model string, tokensIn, tokensOut, latencyMs int, cost float64) error
}

// Ensure QuotaService satisfies QuotaServiceIface.
var _ QuotaServiceIface = (*QuotaService)(nil)
